In [16]:
имя = input('what is your name?')
print ('втоё имя ' + имя)

what is your name?Артур
втоё имя Артур


In [13]:
for a in range(10):
    print(a)

0
1
2
3
4
5
6
7
8
9


In [17]:
y = 9
x = y
y = 7
print (x)

9


In [28]:
x,y = 1,8
print (str(x) + str(y))

18


In [25]:
a = int(input())
if a > 5 and a < 10:
    print ('yeah')


4


In [32]:
a = 123.444
print ("{:10.2f}".format(a))

    123.44


In [33]:
import math
r = float(input('radius ='))
print("%-10s %.2f " % ('area =', math.pi*r*r))


radius =4
area =     50.27 


In [38]:
import random
x = random.randint(1,6)
print (x)

2


In [44]:
for x in range(1,6,2):
    print(x**x)

1
27
3125


In [46]:
k = 0
while k<10:
    print(k)
    k += 1

0
1
2
3
4
5
6
7
8
9


In [47]:
n = int(input())
num = 1
for i in range(n+1):
    print(num)
    num = num * 2
    

4
1
2
4
8
16


In [52]:
n = int(input())
sum = 0

while n>0:
    sum = sum + (n % 10)
    n = n // 10
    
print('sum of digits: ' + str(sum))

167
sum of digits: 14


In [54]:
a,b = 0,1
print(a)
while b<100:
    print(b)
    a,b =b, a+b
    


0
1
1
2
3
5
8
13
21
34
55
89


In [60]:
import math
x = 0.5
s = x 
t = x
eps = 1e-12
k = 1
while math.fabs(t)> eps:
    t *= -x*x/((2*k)*(2*k+1))
    k += 1
    s += t
print(math.sin(x))
print(s)

0.479425538604203
0.479425538604203


In [70]:
max_n =100
for n in range (2, max_n):
        for x in range(2,n):
            if n% x == 0:
                break
        else:
            print (n, 'is a prime number')
                

2 is a prime number
3 is a prime number
5 is a prime number
7 is a prime number
11 is a prime number
13 is a prime number
17 is a prime number
19 is a prime number
23 is a prime number
29 is a prime number
31 is a prime number
37 is a prime number
41 is a prime number
43 is a prime number
47 is a prime number
53 is a prime number
59 is a prime number
61 is a prime number
67 is a prime number
71 is a prime number
73 is a prime number
79 is a prime number
83 is a prime number
89 is a prime number
97 is a prime number


In [69]:
import math
for n in range(2,100):
    for i in range(2, int(math.sqrt(n))+1):
        if n % i == 0:
            break
    else:
        print(n)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [80]:
"""
1.Первая задача этой темы - написать консольную программу, которая вводит целое число a и
вычисляет квадрата числa.
"""
x = int(input("Введи целое число: "))
print ("Квадрат числа " + str(x) + " равен: " + str(x**2))


Введи целое число: 4
Квадрат числа 4 равен: 16


In [85]:
"""
2. Напишите программу, которая вводит численное значение с консоли (не обязательно целое) и
преобразует число дюймов в сантиметры. Для этой цели, умножаем дюймы на 2,54 (потому что 1
дюйм = 2,54 сантиметра).
"""
x = float(input("Введи число: "))
print (str(x)+ " Дюймов = " + str(x*2.54)+ " Сантиметров" )


Введи число: 565
565.0 Дюймов = 1435.1 Сантиметров


In [93]:
"""
1. В этом упражнении мы запросим у пользователя его имя, фамилию, дату рождения и
распечатаем их в определенном формате. Вот пример того, что будет делать программа:.
Введите ваше имя: Aнна
Введите фамилию: Родионова
Введите вашу дату рождения:
Месяц? июль
День? 31
Год? 1997
Aнна Родионова родилась 31 июля 1997 года
"""

имя = input ("Введите ваше имя:")
фамилия = input ("Введите фамилию:")
print("Введите вашу дату рождения:")
месяц = input ("Месяц:")
день = input ("День:")
год = input ("Год:")

if фамилия[-1] == "а": 
    слово = "родилась"
else:
    слово = "родился"
    
месяц_2 = ""
for x in range(len(месяц)-1):
        месяц_2 +=месяц[x]
месяц = месяц_2 + "я" 

print (имя + " " + фамилия + " " + слово + " " + день + " " + месяц + " " + год + " года")

Введите ваше имя:Артур
Введите фамилию:Кулинич
Введите вашу дату рождения:
Месяц:Декабрь
День:16
Год:1990
Артур Кулинич родился 16 Декабря 1990 года


In [101]:
"""
Напишите игру под названием «Угадай значение». Программа будет генерировать случайное
значение между 1 и 100. Пользователь вводит свое значение и получает ответ «Меньше», если
случайное значение меньше чем введенное, «Больше», если случайное значение больше чем
введенное, а также "Верно!", если значение угадано. Игрок может продолжать угадывание до
правильного ответа.

"""
import random
x = random.randint(1,100)
y = 0
while x != y:
    y = int(input("введите число: "))
    if x > y:
        print("Загаданное число больше")
    elif x < y:
        print("Загаданное число меньше")      
print ("Верно! Загаданное число: " + str(y))




введите число: 75
Загаданное число меньше
введите число: 56
Загаданное число меньше
введите число: 43
Загаданное число больше
введите число: 49
Загаданное число меньше
введите число: 45
Верно! Загаданное число:45


In [105]:
def fib(x):
    a,b = 0,1
    print (a)
    while a < x :
        print(b)
        a,b = b,a +b
fib(6)


0
1
1
2
3
5
8


In [109]:
def monthly_payments(loanAmount, interestCalculation,years):
    numberOfPayments = years * 12
    return loanAmount * interestCalculation * (1+interestCalculation) * numberOfPayments / ((1+interestCalculation) * numberOfPayments - 1)
for y in range (1,11):
    mp = monthly_payments(100000,0.11,y)
    print("%.2f \t %.2f" %( mp, mp * y * 12))
    



11892.86 	 142714.29
11429.02 	 274296.41
11282.34 	 406164.27
11210.41 	 538099.46
11167.68 	 670060.98
11139.38 	 802035.48
11119.25 	 934017.35
11104.21 	 1066003.79
11092.53 	 1197993.27
11083.21 	 1329984.87


In [124]:
import math
def nuton(x):
    a0 = x/2
    a1 = x/3
    eps = 1e-9
    while math.fabs(a1-a0) > eps:
        t = a1
        a1=1/2*(a0+x/a0)
        a0 = t
    return a1

if __name__ == "__main__":
    def nut2on(x):
        return(x)
    print (nuton(4), math.sqrt(4))

2.0000000000262146 2.0


In [145]:
import math
def ploT(a, b, c):
    p = 1/2*(a+b+c)
    S = math.sqrt(p*(p-a)*(p-b)*(p-c))
    return S
    
def length_line(x1,y1,x2,y2):
    return ((x2 - x1)**2 + (y2 - y1)**2 )**(1/2)

ax,ay,bx,by,cx,cy,dx,dx = 1,1,1,3,3,1,1.4,1.4

lenthAB = length_line(ax,ay,bx,by)
lenthBC = length_line(bx,by,cx,cy)
lenthCA = length_line(ax,ay,cx,cy)
lenthAD = length_line(ax,ay,dx,dx)
lenthBD = length_line(bx,by,dx,dx)
lenthCD = length_line(dx,dx,cx,cy)
 

triMain=0
triMain = ploT(lenthAB,lenthBC,lenthCA)
triL1 = ploT(lenthAD,lenthCD,lenthCA)
triL2 = ploT(lenthAD,lenthBD,lenthAB)
triL3 = ploT(lenthBD,lenthCD,lenthBC)

print(round(triMain,2) == round((triL1 + triL2 +triL3),2))

True


In [117]:
print (nuton(4), math.sqrt(4))

2.0000000000262146 2.0


In [125]:
nut2on(3)

3

In [127]:
dir(math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [169]:
N  = 10
A = [random.randint(1,100) for i in range(N)]
print(*A)
for x in A:
    print (x, end = ";")
    
print("\n")
print(math.fsum(A[1::2]))


9 97 52 66 89 87 50 13 12 81
9;97;52;66;89;87;50;13;12;81;

344.0


In [170]:
A = [int(x) for x in input().split(";")]
print (*A)

KeyboardInterrupt: Interrupted by user

In [173]:
nums = [1,23,4,5,6,7]
fnums = [true if x%2 == 0 else false if x%2 != 0]
print (*nums)

SyntaxError: invalid syntax (<ipython-input-173-8baf31ef1301>, line 2)

In [192]:
import numpy as np
def print_matrix(m):
    for i in range(len(m)):
        for j in range(len(m[0])):
            print(m[i][j], end = "\t")
        print ("\n")


mt = []
for i in range(10):
    mt.append([])
    for j in range(10):
        mt[i].append((i+1)*(j+1))
        
print_matrix (mt)
 

        
        

1	2	3	4	5	6	7	8	9	10	

2	4	6	8	10	12	14	16	18	20	

3	6	9	12	15	18	21	24	27	30	

4	8	12	16	20	24	28	32	36	40	

5	10	15	20	25	30	35	40	45	50	

6	12	18	24	30	36	42	48	54	60	

7	14	21	28	35	42	49	56	63	70	

8	16	24	32	40	48	56	64	72	80	

9	18	27	36	45	54	63	72	81	90	

10	20	30	40	50	60	70	80	90	100	



In [188]:
import numpy as np
  
# Taking a 3 * 3 matrix
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
  
# Calculating the inverse of the matrix
print(np.linalg.inv(A))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [211]:
d = {"1":"end", "2":"water"}
#print (d["duck"])
#del d["duck"]

d["3"] = "dasd"
print(sorted(d, key=lambda t:t[0]))



['1', '2', '3']


In [18]:
mt = {}
i = 0
j= 0
sm = 0
strrr = ""
while input() != "Нет":
    strrr = input()
    mt[strrr] =  input()
    print (mt)
    mx = 0
    for t in mt.values():
        j += 1
        sm += float(t)
        if mx < float(t):
            mx = float(t)
    sr = sm/j
    
print(sr, " max:", mx)





ывпаывпаы
43
{'ывпаывпаы': '43'}

ыаываы
65
{'ывпаывпаы': '43', 'ыаываы': '65'}
Нет
50.333333333333336  max: 65.0


In [14]:
my2DList = [[13,18,21], [30,40,50], [77,88,99]]
my2DList[0][2] = 25
my2DList.append([101, 121])
del my2DList[1][1]

print(my2DList)


[[13, 18, 25], [30, 50], [77, 88, 99], [101, 121]]


In [18]:
def isPosindr(txt):
    #print(len(txt))
    i = -1
    cnt = 0
    for t in txt: 
        if str(t).upper() != str(txt[i]).upper():
            break
        else:
            cnt += 1
        i -= 1
        #print(t)
    if cnt == len(txt):
        print(True)
    else:
        print(False)
        
        
import re
txt = input()
isPosindr(txt)


True


In [41]:
import re
dre=re.compile(r"[,-.()\n ]")
lst = {}
txt = """Напишите функцию is_palindrome (s), которая принимает строку s и возвращает значение True,
если s является палиндром и возвращает False в противном случае. Палиндром - это слово,
которое читается одинаково слево-направо, и справо-налево, например abba, madam, kayak, radar
и rotator, АРОЗАУПАЛАНАЛАПУАЗОРА."""
for wrd in dre.split(txt):
    if len(wrd)>0:
        #lst.append(str(wrd))
        if wrd in lst:
            #print(wrd)
            lst[wrd] += 1
        else:
            #print(wrd)
            lst[wrd] = 1
print(sorted(lst.items(), key=lambda kv: kv[1],reverse=True))



[('и', 4), ('s', 3), ('возвращает', 2), ('Напишите', 1), ('функцию', 1), ('is_palindrome', 1), ('которая', 1), ('принимает', 1), ('строку', 1), ('значение', 1), ('True', 1), ('если', 1), ('является', 1), ('палиндром', 1), ('False', 1), ('в', 1), ('противном', 1), ('случае', 1), ('Палиндром', 1), ('это', 1), ('слово', 1), ('которое', 1), ('читается', 1), ('одинаково', 1), ('слево', 1), ('направо', 1), ('справо', 1), ('налево', 1), ('например', 1), ('abba', 1), ('madam', 1), ('kayak', 1), ('radar', 1), ('rotator', 1), ('АРОЗАУПАЛАНАЛАПУАЗОРА', 1)]


In [92]:
import pdb
import random

#pdb.set_trace()

words = ["книга", "месяц", "ручка", "шарик", "олень", "носок"]
#print(random.randint(0,5))
thisWord = words[random.randint(0,5)]
#print(thisWord)
wordsGues = ["\u25A0","\u25A0","\u25A0","\u25A0","\u25A0"]
health = 3
print(wordsGues, "\t| x", health)
guess = 0
while health > 0:
    g = input("Введите букву или слово целиком: ")
    if len(g) > 1:
        if g == thisWord:
            print(str(thisWord).upper(), "\t| x", health)
            print("Вы выиграли")
            break
        else:
            print("Неправильно")
            health -= 1
            print(wordsGues, "\t| x", health)
    else: 
        i = 0
        j = 0
        for symb in thisWord:
            if str(symb).upper() == str(g).upper():
                wordsGues[i] = str(g).upper()
                j +=1
                #print("ok")
            #else:
                #print("not OK2")
            i += 1
        if j == 0:
            health -= 1
            print(wordsGues, "\t| x", health)
        else:
            print(wordsGues, "\t| x", health)
        #print(wordsGues)
        
        


['■', '■', '■', '■', '■'] 	| x 3
Введите букву или слово целиком: м
['■', '■', '■', '■', '■'] 	| x 2
Введите букву или слово целиком: с
['■', '■', '■', '■', '■'] 	| x 1
Введите букву или слово целиком: р
['Р', '■', '■', '■', '■'] 	| x 1
Введите букву или слово целиком: ручка
РУЧКА 	| x 1
Вы выиграли


In [1]:
pip install ipykernel --pre


Note: you may need to restart the kernel to use updated packages.
